version : '3'
services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile      
    container_name: rapidPrintBackend
    ports:
      - 8080:8080   
    volumes:
      - ./:/var/www
   
  redis:
    image: redis:alpine
    container_name: radis

    hostname: redis  
    ports:
      - "6070:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
   


